.TH COQ 1 "April 25, 2001"

.SH NAME
coq-interface \-


.SH SYNOPSIS
.B coq-interface
[
.B options
]

.SH DESCRIPTION

.B coq-interface
is a Coq customized toplevel system for Coq containing some modules
useful for the graphical interface. This program is not for the casual
user.

.SH OPTIONS

.TP
.B \-h
Help. Will give you the complete list of options accepted by
coq-interface (the same as coqtop).

.SH SEE ALSO

.BR coqc (1),
.BR coqdep (1),
.BR coqtop (1),
.BR parser (1).
.br
.I
The Coq Reference Manual.
.I
The Coq web site: http://coq.inria.fr
