.TH COQ 1 "April 25, 2001"

.SH NAME
coq\-parser \- Coq parser


.SH SYNOPSIS
.B coq\-parser
[
.B options
]

.SH DESCRIPTION

.B parser
is a program reading Coq proof developments and outputing them in the
structured format given in the INRIA technical report RT154. This
program is not for the casual user.

.SH SEE ALSO

.BR coq\-interface (1),
.BR coqc (1),
.BR coqtop (1),
.BR coqdep (1).
.br
.I
The Coq Reference Manual.
.I
The Coq web site: http://coq.inria.fr
