.\" TODO: actually document this thing
.TH COQ_MAKEFILE 1
.
.SH NAME
coq_makefile \- generate makefiles for Coq proof development
.
.
.SH SYNOPSIS
.B coq_makefile
[
.I arguments
]
.
.SH DESCRIPTION
.
.B coq_makefile
is a makefile generator for Coq proof developments.
.
.SH OPTIONS
.
.TP
.B \-h
Will give you a description of the whole list of options of
.BR coq_makefile .
.
.SH SEE ALSO
.
.BR coqtop (1),
.BR coqtc (1),
.BR coqdep (1)
.PP
.I
The Rocq Prover Reference Manual.
.PP
The Rocq Prover website: https://rocq-prover.org
