.TH coqdoc 1 "February, 2002"

.SH NAME
coqdoc \- A documentation tool for the Coq proof assistant


.SH SYNOPSIS
.B coqdoc
[
.B options
]
.B files


.SH DESCRIPTION

.B coqdoc
is a documentation tool for the Coq proof assistant.
It creates LaTeX or HTML documents from a set of Coq files.
See the Coq reference manual for documentation (url below).


.SH OPTIONS

.TP
.B \-h
Help. Will give you the complete list of options accepted by coqdoc.


.SH SEE ALSO

.I
The Coq web site: http://coq.inria.fr/
