.TH COQDEP 1
.
.SH NAME
coqdep \- compute inter-module dependencies for Coq programs
.
.SH SYNOPSIS
.B coqdep
[
.BI \-I \ directory
]
[
.BI \-coqlib \ directory
]
[
.B \-i
]
[
.B \-slash
]
.I filename .\|.\|.\&
.I directory .\|.\|.
.
.SH DESCRIPTION
.
.B coqdep
computes inter-module dependencies for Coq programs,
and prints the dependencies on the standard output in a format
readable by
.BR make .
When a directory is given as argument, it is recursively looked at.
.PP
Dependencies of Coq modules are computed by looking at
.I Require
commands (Require, Require Export, Require Import, possibly restricted by a From clause),
.I Declare
.I ML
.I Module
commands,
.I Add
.I LoadPath
commands and
.I Load
commands.
Dependencies relative to modules from the Coq library are not
printed except if
.B \-boot
is given.
.
.SH OPTIONS
.
.TP
.BI \-f \ file
Read filenames and options
.BR \-I ,
.B \-R
and
.B \-Q
from a _CoqProject
.I file.
.TP
.BI \-I\fR/\fB\-Q\fR/\fB\-R \ options
Have the same effects on load path and modules names as for other
Coq commands (\c
.BR coqtop ,
.BR coqc ).
.TP
.BI \-coqlib \ directory
Indicates where is the Coq library.
The default value has been determined at installation time, and
therefore this option should not be used under normal circumstances.
.TP
.BI \-exclude-dir \ dir
Skips subdirectory
.I dir
during
.BR \-R / \-Q
search.
.TP
.B \-sort
Output the given file name ordered by dependencies.
.TP
.B \-vos
Output dependencies for .vos files (this is not the default as it breaks
dune's Coq mode).
.TP
.B \-boot
For Coq developers, prints dependencies over Coq library files
(omitted by default).
.TP
.B \-noinit
Currently no effect.
.TP
.B \-vos
Includes dependencies about .vos files.
.TP
.BR \-dyndep \ ( opt | byte | both | no | var )
Set how dependencies over ML modules are printed.
.TP
.BI \-m \ meta
Resolve plugin names using the
.I meta
file.
.TP
.BI \-w \ w1,\|.\|.\|.\|,\|wn
Configure display of warnings as for
.BR coqc .
.
.SH EXIT STATUS
.IP 1
A file given on the command line cannot be found, or some file
cannot be opened, or there is a syntax error in one of the commands
recognized by
.BR coqdep .
.IP 0
In all other cases.
In particular, when a dependency cannot be found or an invalid option is
encountered,
.B coqdep
prints a warning and exits with status 0.
.
.
.SH SEE ALSO
.
.BR ocamlc (1),
.BR coqc (1),
.BR make (1)
.
.SH NOTES
.
Lexers (for Coq and OCaml) correctly handle nested comments
and strings.
.PP
The treatment of symbolic links is primitive.
.PP
If two files have the same name, in two different directories,
a warning is printed on standard error.
.PP
There is no way to limit the scope of the recursive search for
directories.
.
.SH EXAMPLES
.
Consider the files (in the same directory):
.RS
a.mllib, X.v, Y.v, and Z.v
.RE
where
.IP \(bu 3
a.mllib contains the module names `B' and `C';
.IP \(bu
Y.v contains the command `Require Foo.X';
.IP \(bu
Z.v contains the commands `From Foo Require X' and `Declare ML Module "a"'.
.PP
To get the dependencies of the Coq files:
.PP
.RS
.nf
example% coqdep \-I . \-Q . Foo *.v

X.vo X.glob X.v.beautified X.required_vo: X.v
Y.vo Y.glob Y.v.beautified Y.required_vo: Y.v X.vo
Z.vo Z.glob Z.v.beautified Z.required_vo: Z.v X.vo ./a.cma ./a.cmxs
.fi
.RE
.
.SH BUGS
.
Please report any bug to
.BR https://github.com/coq/coq/issues .
