.TH COQTOP.BYTE 1
.
.SH NAME
coqtop.byte \- bytecode toplevel Coq system
.
.
.SH SYNOPSIS
.B coqtop.byte
[
options
]
[
.I file
]
.
.SH DESCRIPTION
.
.B coqopt.byte
is the bytecode version of Coq.
It should not be called directly, but only by
.B coqtop
and
.BR coqc .
.
.SH SEE ALSO
.
.BR coqtop (1),
.BR coqc (1)
.PP
.I
The Rocq Prover Reference Manual.
.PP
The Rocq Prover website: https://rocq-prover.org
