.TH COQ 1 "April 25, 2001"

.SH NAME
coqtop.byte \- The bytecode Coq toplevel


.SH SYNOPSIS
.B coqtop.byte
[
.B options
]
[
.I file
]

.SH DESCRIPTION

.B coqopt.byte
is the bytecode version of Coq. It should not be called directly, but
only by
.B coqtop
and
.B coqc

.SH SEE ALSO

.BR coqtop (1),
.BR coqc (1).
.br
.I
The Coq Reference Manual.
.I
The Coq web site: http://coq.inria.fr


