.TH COQWC 1
.
.SH NAME
coqwc \- print the number of specification, proof and comment lines in
Coq files
.
.SH SYNOPSIS
.B coqwc
[
.B \-p
]
[
.B \-s
]
[
.B \-r
]
[
.B \-e
]
.I files .\|.\|.
.
.SH DESCRIPTION
.
.B coqwc
computes the number of specification lines, proof lines and comment
lines in Coq files.
.
.SH OPTIONS
.
.TP
.B \-p
Print the percentage of comments.
.TP
.B \-s
Print only the number of specification lines.
.TP
.B \-r
Print only the number of proof lines.
.TP
.B \-e
Do not skip headers.
.
.SH BUGS
.
Please report any bug to
.BR https://github.com/coq/coq/issues .
