.TH ROCQ 1
.
.SH NAME
rocq \- The Rocq Prover
.
.
.SH SYNOPSIS
.B rocq
[
.BI \-debug-shim
]
[
.BI \-v
.BI |
.BI \-\-version
]
[
subcommand
]
[
subcommand options
]
.
.SH DESCRIPTION
.
.B rocq
is the Rocq prover.
.
.SH SEE ALSO
.
.BR rocq (1),
.PP
.I
The Rocq Reference Manual.
.PP
The Rocq web site: http://coq.inria.fr
