#!/bin/sh

FLAGS=
OCAMLBUILD=ocamlbuild

check_config() {
 [ -f config/coq_config.ml ] || (echo "please run ./configure first"; exit 1)
 [ -L myocamlbuild_config.ml ] || ln -sf config/coq_config.ml myocamlbuild_config.ml
}

ocb()
{
  check_config
  $OCAMLBUILD $FLAGS $*
}

rule() {
  case $1 in
    win32)  check_config
            sed -i 's/let arch = .*$/let arch = "win32"/' config/coq_config.ml && \
	    $OCAMLBUILD toplevel/coqtop.native plugins/pluginsopt.otarget;;
    clean)  ocb -clean && rm -rf bin/* && rm -f myocamlbuild_config.ml;;
    all)    ocb coq.otarget;;
    *)      ocb $1;;
  esac;
}

if [ $# -eq 0 ]; then
  rule all
else
  while [ $# -gt 0 ]; do
    rule $1;
    shift
  done
fi
