#!/bin/sh

FLAGS=
OCAMLBUILD=ocamlbuild
CFG=config/coq_config.ml
MYCFG=myocamlbuild_config.ml

check_config() {
 [ -f $CFG ] || (echo "please run ./configure first"; exit 1)
 [ -L $MYCFG ] || ln -sf $CFG $MYCFG
}

ocb() { $OCAMLBUILD $FLAGS $*; }

rule() {
  check_config
  case $1 in
    win32)  cp $CFG $CFG.initial && chmod 644 $CFG && \
	    echo 'let arch = "win32"' >> $CFG &&
	    ocb coq-win32.otarget
	    mv -f $CFG.initial $CFG;;
    clean)  ocb -clean && rm -rf bin/* && rm -f $MYCFG;;
    all)    ocb coq.otarget;;
    *)      ocb $1;;
  esac;
}

if [ $# -eq 0 ]; then
  rule all
else
  while [ $# -gt 0 ]; do
    rule $1;
    shift
  done
fi
