#!/bin/sh

FLAGS=
OCAMLBUILD=ocamlbuild
CFG=config/coq_config.ml
MYCFG=myocamlbuild_config.ml

export CAML_LD_LIBRARY_PATH=`pwd`/_build/kernel/byterun

check_config() {
 [ -f $CFG ] || (echo "please run ./configure first"; exit 1)
 [ -L $MYCFG ] || ln -sf $CFG $MYCFG
}

ocb() { $OCAMLBUILD $FLAGS $*; }

rule() {
  check_config
  case $1 in
    clean)  ocb -clean && rm -rf bin/* && rm -f $MYCFG;;
    all)    ocb coq.otarget;;
    win32)  ocb coq-win32.otarget;;
    *)      ocb $1;;
  esac;
}

if [ $# -eq 0 ]; then
  rule all
else
  while [ $# -gt 0 ]; do
    rule $1;
    shift
  done
fi
