.PHONY: contrib-all contrib-hott contrib-math-comp

contrib-all: contrib-hott contrib-math-comp

# TODO Do generic rule
contrib-hott:
	./tools/ci/contrib-hott.sh

contrib-math-comp:
	./tools/ci/contrib-math-comp.sh

contrib-compcert:
	./tools/ci/contrib-compcert.sh
