CI_TARGETS=ci-all ci-hott ci-math-comp ci-compcert ci-sf ci-cpdt	\
           ci-color ci-math-classes ci-tlc ci-fiat-crypto		\
           ci-coquelicot ci-flocq ci-iris-coq ci-metacoq

.PHONY: $(CI_TARGETS)

# Generic rule, we use make to easy travis integraton with mixed rules
$(CI_TARGETS): ci-%:
	./tools/ci/ci-$*.sh

