.TH COQ 1 "April 25, 2001"

.SH NAME
coq_makefile \- The Coq Proof Assistant makefile generator


.SH SYNOPSIS
.B coq_makefile
[
.B arguments
]

.SH DESCRIPTION

.B coq_makefile
is a makefile generator for Coq proof developments.

.SH OPTIONS

.TP
.BI \-h
Will give you a description of the whole list of options of coq_makefile.

.SH SEE ALSO

.BR coqtop (1),
.BR coqtc (1),
.BR coqdep (1).
.br
.I
The Coq Reference Manual.
.I
The Coq web site: http://coq.inria.fr
