.TH COQ 1 "April 25, 2001"

.SH NAME
coqc \- The Coq Proof Assistant compiler


.SH SYNOPSIS
.B coqc
[
.B general \ Coq \ options
]
.I file


.SH DESCRIPTION

.B coqc
is the batch compiler for the Coq Proof Assistant.
The options are basically the same as coqtop(1).
.IR file.v \&
is the vernacular file to compile.
.IR file \& 
must be formed
only with the characters `a` to  `Z`, `0`-`9` or `_` and must begin
with a letter.
The compiler produces an object file
.IR file.vo \&.

For interactive use of Coq, see 
.BR coqtop(1).


.SH OPTIONS

.B coqc
is a script that simply runs
.B coqtop
with option 
.B \-compile
it accepts the same options as
.B coqtop.

.SH SEE ALSO

.BR coqtop (1),
.BR coq_makefile (1),
.BR coqdep (1).
.br
.I
The Coq Reference Manual.
.I
The Coq web site: http://coq.inria.fr
