.TH COQ 1 "April 25, 2001"

.SH NAME
coqtop.opt \- The native-code Coq toplevel


.SH SYNOPSIS
.B coqopt.opt
[
.B options
]
[
.I file
]

.SH DESCRIPTION

.B coqopt.opt
is the native-code version of Coq. It should not be called directly, but
only by
.B coqtop
and
.B coqc

.SH SEE ALSO

.BR coqtop (1),
.BR coqc (1).
.br
.I
The Coq Reference Manual.
.I
The Coq web site: http://coq.inria.fr


