# to be linked to makefile (lowercase - takes precedence over Makefile)
# in main directory

TOPDIR=.
BASEDIR=

SOURCEDIRS=lib kernel library pretyping parsing proofs tactics toplevel

default:	noargument

# set the devel makefile
setup-devel:
	@ln -sfv dev/Makefile.devel makefile
	@(for i in $(SOURCEDIRS); do \
	    (cd $(TOPDIR)/$$i; ln -sfv ../dev/Makefile.dir Makefile) \
	done)

clean-devel:
	echo rm -f makefile .depend.devel
	echo rm -f $(foreach dir,$(SOURCEDIRS), $(TOPDIR)/$(dir)/Makefile)

coqtop:
	ln -sf bin/coqtop.byte coqtop


include Makefile

include $(TOPDIR)/dev/Makefile.common

# this file is better described in dev/Makefile.dir
include .depend.devel

total:
	ledit ./bin/coqtop.byte $(foreach th,$(THEORIESVO),-require $(notdir $(basename $(th))))
