# this Makefile contains goals common for directory and main devel makefiles

ifndef TOPDIR
TOPDIR=..
endif

ifndef BASEDIR
BASEDIR=
endif

# the following entries are used to make synchronize two source trees
# (on big computer and on a laptop for example)

OTHER_FILE=$(TOPDIR)/dev/other
OTHER=$(shell cat $(OTHER_FILE))

# this is a directory of useful temporary things
WORKDIR=tmp

check_other:
	@(if [ "$(OTHER)" = "" ] ; then \
	  echo You must put the ssh path to the other Coq source in $(OTHER_FILE) ; \
	  echo For example: chrzaszc@ruta:coq/V7 ; \
	  exit 1; \
	fi)

get:	check_other
	rsync -Cauvz $(OTHER)/ $(TOPDIR)/
	@(if [ -d $(TOPDIR)/$(WORKDIR) ]; then \
	  rsync -auvz $(OTHER)/tmp/ $(TOPDIR)/tmp/ ; \
	fi)

put:	check_other
	rsync -Cauvz $(TOPDIR)/ $(OTHER)/
	@(if [ -d $(TOPDIR)/$(WORKDIR) ]; then \
	  rsync -auvz $(TOPDIR)/tmp/ $(OTHER)/tmp/ ; \
	fi)

sync:	get put
