#!/bin/sh

# wrap around ocamldebug for Coq

export COQTOP=$constr/V7
export CAMLP4LIB=`camlp4 -where`
CAMLBIN=`which ocamlc`
OCAMLDEBUG=`dirname $CAMLBIN`/ocamldebug

exec $OCAMLDEBUG \
	-I $CAMLP4LIB \
	-I $COQTOP/lib \
	-I $COQTOP/dev \
	-I $COQTOP/kernel \
	-I $COQTOP/parsing \
        -I $COQTOP/toplevel \
	$*


