#!/bin/sh

# wrap around ocamldebug for Coq

export COQTOP='/home/herbelin/COQ/newgit/v8.0'
export COQLIB='/home/herbelin/COQ/newgit/v8.0'
export COQTH=$COQLIB/theories
CAMLBIN='/home/herbelin/.opam/4.02.3--coq-8.4pl6/bin'
OCAMLDEBUG=$CAMLBIN/ocamldebug
if [ -x "$CAMLBIN/camlp5" ]; then 
  export CAMLP4LIB=`$CAMLBIN/camlp5 -where`
else
  export CAMLP4LIB=`$CAMLBIN/camlp4 -where`
fi

args=""
coqdebug="no"
for op in $*
    do case `basename $op` in
	coq-debug-programs.out) 
	    coqdebug="yes"
	    args="-is programs.coq";;
	*coq*) coqdebug="yes";;
       esac
done

case $coqdebug in
    yes)
	exec $OCAMLDEBUG \
	-I $CAMLP4LIB \
	-I $COQTOP/config \
	-I $COQTOP/lib -I $COQTOP/kernel \
	-I $COQTOP/library -I $COQTOP/pretyping -I $COQTOP/parsing \
        -I $COQTOP/interp -I $COQTOP/proofs -I $COQTOP/tactics \
	-I $COQTOP/toplevel -I $COQTOP/dev -I $COQTOP/config \
	-I $COQTOP/translate \
        -I $COQTOP/contrib/correctness \
        -I $COQTOP/contrib/extraction -I $COQTOP/contrib/field \
        -I $COQTOP/contrib/fourier    -I $COQTOP/contrib/graphs \
        -I $COQTOP/contrib/interface  -I $COQTOP/contrib/jprover \
        -I $COQTOP/contrib/omega      -I $COQTOP/contrib/romega \
        -I $COQTOP/contrib/ring       -I $COQTOP/contrib/xml \
	$* $args;;
    *) exec $OCAMLDEBUG $*;;
esac
