#!/bin/sh
rm -f /tmp/extr$$.v
cat > /tmp/extr$$.v << EOF
Cd "theories/Reals".
Require Reals.
Extract Constant R => float.
Extract Constant R0 => "0.0".
Extract Constant R1 => "1.0".
Extract Constant Rplus => "(+.)".
Extract Constant Rmult => "( *.)".
Extract Constant Ropp => "(~-.)".
Extract Constant Rinv => "(fun x -> 1.0 /. x)".
Extract Constant Rlt => "(<)".
Extract Constant up => "AddReals.my_ceil".
Extract Constant total_order_T => "AddReals.total_order_T".
EOF
for f in $*; do
    ff=`basename $f .vo`
    echo "Require $ff." >> /tmp/extr$$.v
    echo "Extraction Module $ff." >> /tmp/extr$$.v
done
../../../bin/coqtop.opt -silent -batch -load-vernac-source /tmp/extr$$.v
out=$?
#rm -f /tmp/extr$$.v
exit $out


