(* DO NOT EDIT THIS FILE: automatically generated by ../configure *)

let local = true
let bindir = "/home/herbelin/COQ/newgit/v8.0/bin" 
let coqlib = "/home/herbelin/COQ/newgit/v8.0"
let coqtop = "/home/herbelin/COQ/newgit/v8.0"
let camllib = "/home/herbelin/.opam/4.02.3--coq-8.4pl6/lib/ocaml"
let camlp4 = "camlp5"
let camlp4lib = "/home/herbelin/.opam/4.02.3--coq-8.4pl6/lib/ocaml/camlp4"
let best = "opt"
let arch = "x86_64"
let osdeplibs = "-cclib -lunix"
let version = "8.0pl3"
let caml_version = "4.02.3"
let versionsi = ""
let date = "Jan 2006"
let compile_date = "nov. 29 2015 16:33:47"
let exec_extension = ""

let theories_dirs = [
"Arith";
"Bool";
"Classes";
"FSets";
"Init";
"IntMap";
"Lists";
"Logic";
"MSets";
"NArith";
"Num";
"Num/Nat";
"Num/Leibniz";
"Program";
"QArith";
"Reals";
"Relations";
"Setoids";
"Sets";
"Sorting";
"Strings";
"Structures";
"Unicode";
"Wellfounded";
"ZArith";
]
let contrib_dirs = [
"cc";
"extraction";
"field";
"first-order";
"fourier";
"funind";
"interface";
"jprover";
"omega";
"ring";
"romega";
"xml";
]
