#!/usr/bin/env sh

## This file should be run from the root of the Coq source tree

BRANCH=$(git rev-parse --abbrev-ref HEAD)
echo "Branch: $BRANCH in $PWD"

if [ "$#" -ne 1 ]; then
  PROJECT=""
else
  PROJECT="--argstr project $1"
fi

if [ "$BN" ]; then
  BN="--argstr bn ${BN}"
else
  BN=""
fi

nix-shell ./dev/ci/nix/ --show-trace --argstr wd $PWD --argstr branch $BRANCH $PROJECT $BN
