# if you work in a sub/sub-rectory of Coq
# you should make a link to that makefile 
#    ln -s ../../dev/tools/Makefile.subdir Makefile
# in order to have all the facilities of dev/tools/Makefile.dir

TOPDIR=../..
include $(TOPDIR)/dev/tools/Makefile.dir
