#!/bin/bash

TAG="$1"

if [ -z "$TAG" ]; then
  echo "usage: $0 tagname"
  exit 1
fi

case $TAG in
  V*+rc*)
    OPAM_DIR="--packages-directory=core-dev/packages"
    OPAM_REPO="--repo=coq/opam-coq-archive"
  ;;

  *)
    # defauls are good for the main OPAM repo
    OPAM_DIR=
    OPAM_REPO=
  ;;
esac

URL="https://github.com/coq/coq/releases/download/$TAG/coq-${TAG##V}.tar.gz"

echo "Publishing tag $TAG for url $URL"
echo
echo "The url corresponds to a release asset, not the tarball generated by git,"
echo "hence you have to download that tarball and re-upload it as an asset!"
echo "This prevents the sha to change over time (as github updated git)."
echo
echo "Hit ^C to stop, or type opam-publish options (eg -n for dry run) and return to continue:"
read OPTS
opam-publish --tag=$TAG $OPAM_DIR $OPAM_REPO -v ${TAG##V} $OPTS "$URL" coq-core.opam coqide.opam coq.opam coqide-server.opam coq-stdlib.opam

