#! /bin/sh

echo "This shell script performs the following transformations:"
echo "- Insertion of a space after a dot not followed by a separator"
echo "- Insertion of a space between consecutive ~ and < and between"
echo "  consecutive | and < assumed to be part of distinct tokens"
echo "- Various renamings of commands as described in document Changes.ps"

for i in $*
  do sed -e "s/\.\([A-Z]\)/\. \1/g" -e "s/AddPath/Add LoadPath/g" \
    -e "s/~</~ </g" -e "s/|</| </g" -e "s/\([^ ]\)\?/\1 \?/g" \
    -e "s/\?\([^ ]\)/\? \1/g" \
    -e "s/AddPath/Add LoadPath/g" -e "s/DelPath/Remove LoadPath/g" \
    -e "s/AddRecPath/Add Rec LoadPath/g" \
    -e "s/Implicit  *Arguments  *On/Set Implicit Arguments/g" \
    -e "s/Implicit *Arguments *Off/Unset Implicit Arguments/g" \
    -e "s/Begin *Silent/Set Silent/g" -e "s/End *Silent/Unset Silent/g" \
    -e "s/Print *Path/Print Coercion Paths/g" \
    $i > $i.tmp$$
  if diff $i.tmp$$ $i > /dev/null
    then
      rm $i.tmp$$
    else
      echo Le fichier $i a été modifié
      mv $i.tmp$$ $i
  fi
  done
echo
