overlay coq_dpdgraph https://github.com/ppedrot/coq-dpdgraph compact-case-repr 13563
overlay coqhammer https://github.com/ppedrot/coqhammer compact-case-repr 13563
overlay elpi https://github.com/ppedrot/coq-elpi compact-case-repr 13563
overlay equations https://github.com/ppedrot/Coq-Equations compact-case-repr 13563
overlay metacoq https://github.com/ppedrot/metacoq compact-case-repr 13563
overlay mtac2 https://github.com/ppedrot/Mtac2 compact-case-repr 13563
overlay paramcoq https://github.com/ppedrot/paramcoq compact-case-repr 13563
overlay relation_algebra https://github.com/ppedrot/relation-algebra compact-case-repr 13563
overlay unicoq https://github.com/ppedrot/unicoq compact-case-repr 13563
