name: GitHub CI

on: [push, pull_request]

jobs:
  macOS:
    runs-on: macOS-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          brew tap discoteq/discoteq
          brew install gnu-time opam gtksourceview3 adwaita-icon-theme flock
          pip3 install macpack

      - name: Install OCaml dependencies
        run: |
          export PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig
          opam init -a -j "$NJOBS" --compiler=ocaml-base-compiler.$COMPILER
          opam switch set ocaml-base-compiler.$COMPILER
          eval $(opam env)
          opam update
          opam install -j "$NJOBS" ocamlfind${FINDLIB_VER} ounit lablgtk3-sourceview3 zarith.1.10 dune.2.8.5
          opam list
        env:
          COMPILER: "4.11.1"
          FINDLIB_VER: ".1.8.1"
          OPAMYES: "true"
          MACOSX_DEPLOYMENT_TARGET: "10.11"
          NJOBS: "2"

      - name: Build Coq
        run: |
          eval $(opam env)
          ./configure -prefix "/usr/local" -warn-error yes -native-compiler no -coqide opt
          make -j "$NJOBS" byte
          make -j "$NJOBS"
          dune build coq-core.install
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.11"
          NJOBS: "2"

      - name: Install Coq
        run: |
          eval $(opam env)
          sudo make install install-byte

      - name: Run Coq Test Suite
        run: |
          eval $(opam env)
          export OCAMLPATH="/usr/local/lib":"$OCAMLPATH"
          make -j "$NJOBS" test-suite PRINT_LOGS=1
        env:
          NJOBS: "2"

      - name: Test that Coq runs from env
        run: |
          eval $(opam env)
          coqc --config
          coqc --version
          true | coqtop
