name: GitHub CI

on: [push, pull_request]

jobs:
  Windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        architecture:
          # - '32'
          - '64'

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Git checkout
        uses: actions/checkout@v2

      - name: System Information
        run: |
          .\dev\ci\platform\coq-pf-01-sysinfo.bat

      - name: Download Platform
        env:
          PLATFORM: "https://github.com/coq/platform/archive/dev-ci.zip"
        run: |
          .\dev\ci\platform\coq-pf-02-download.bat

      - name: Build Platform
        env:
          ARCH: ${{matrix.architecture}}
        shell: cmd
        run: |
          .\dev\ci\platform\coq-pf-03-build.bat

      - name: Build Installer
        env:
          ARCH: ${{matrix.architecture}}
        shell: cmd
        run: |
          .\dev\ci\platform\coq-pf-04-installer.bat

      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: windows-installer
          path: artifacts
          if-no-files-found: error

  macOS:
    runs-on: macOS-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          brew install gnu-time opam gtksourceview3 adwaita-icon-theme expat libxml2
          pip3 install macpack

      - name: Install OCaml dependencies
        run: |
          export PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig
          opam init -a -j "$NJOBS" --compiler=ocaml-base-compiler.$COMPILER
          opam switch set ocaml-base-compiler.$COMPILER
          eval $(opam env)
          opam update
          opam install -j "$NJOBS" ocamlfind${FINDLIB_VER} ounit lablgtk3-sourceview3 zarith.1.10 dune.2.8.5
          opam list
        env:
          COMPILER: "4.12.0"
          FINDLIB_VER: ".1.8.1"
          OPAMYES: "true"
          MACOSX_DEPLOYMENT_TARGET: "10.11"
          NJOBS: "2"

      - name: Build Coq
        run: |
          eval $(opam env)
          ./configure -prefix "$(pwd)/_install_ci" -warn-error yes -native-compiler no -coqide opt
          make -f Makefile.make -j "$NJOBS" byte
          make -f Makefile.make -j "$NJOBS"
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.11"
          NJOBS: "2"

      - name: Install Coq
        run: |
          eval $(opam env)
          make -f Makefile.make install install-byte

      - name: Run Coq Test Suite
        run: |
          eval $(opam env)
          export OCAMLPATH="$(pwd)/_install_ci/lib":"$OCAMLPATH"
          make -f Makefile.make -j "$NJOBS" test-suite PRINT_LOGS=1
        env:
          NJOBS: "2"
